% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment2},
  pdfauthor={483670 \& 630516},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{lscape}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Assignment2}
\author{483670 \& 630516}
\date{08/09/2022}

\begin{document}
\maketitle

\hypertarget{q1}{%
\section{Q1}\label{q1}}

The mean probability of having benefits in week 10 of those without
search period is \(73.6%
\). For those with the search period treatment this is \(57.2%
\). The probability of still having benefits in week 30 is \(54%
\) for those without and \(41.4%
\) for those with search treatment. In the most naive estimation it
seems that the search treatment decreases the probability of being on
benefits both 10 and 30 weeks after the initial claim.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prob10nosearch }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0}\NormalTok{])}
\NormalTok{prob10search }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\NormalTok{prob30nosearch }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0}\NormalTok{])}
\NormalTok{prob30search }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\hypertarget{q2}{%
\section{Q2}\label{q2}}

The balance table is provided is provided in table \ref{tab:balance} The
potential points of concern for the balance between control and
treatment groups are the differences in age, slight unbalance in the
locations and the difference in shares of unknown education.
Particularly those with unknown education could be problematic. IT MAY
BE GOOD TO EXCLUDE THEM

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{balance }\OtherTok{\textless{}{-}} \FunctionTok{balance\_table}\NormalTok{(data, }\StringTok{"searchperiod"}\NormalTok{)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(balance, }\AttributeTok{caption =} \StringTok{"Balance Table"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:2}Balance Table}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
variables1 & Media\_control1 & Media\_trat1 & p\_value1\\
\hline
age & 39.9258850 & 37.2592105 & 0.0000000\\
\hline
benefits\_week10 & 0.7359116 & 0.5723684 & 0.0000000\\
\hline
benefits\_week30 & 0.5403315 & 0.4144737 & 0.0000003\\
\hline
children & 0.1635359 & 0.1144737 & 0.0036995\\
\hline
educ\_bachelormaster & 0.2640884 & 0.2671053 & 0.8896809\\
\hline
educ\_prepvocational & 0.2176796 & 0.2000000 & 0.3763510\\
\hline
educ\_primaryorless & 0.1303867 & 0.1486842 & 0.2845937\\
\hline
educ\_unknown & 0.0143646 & 0.0500000 & 0.0000599\\
\hline
educ\_vocational & 0.3734807 & 0.3342105 & 0.0948282\\
\hline
female & 0.3971239 & 0.3723684 & 0.3012313\\
\hline
location1 & 0.1767956 & 0.1131579 & 0.0002088\\
\hline
location2 & 0.1823204 & 0.2315789 & 0.0138131\\
\hline
location3 & 0.3734807 & 0.3000000 & 0.0015247\\
\hline
location4 & 0.1005525 & 0.2223684 & 0.0000000\\
\hline
location5 & 0.1668508 & 0.1328947 & 0.0522560\\
\hline
partner & 0.1259669 & 0.1065789 & 0.2177481\\
\hline
period1 & 0.2640884 & 0.2223684 & 0.0475789\\
\hline
period2 & 0.2563536 & 0.2328947 & 0.2669553\\
\hline
period3 & 0.2651934 & 0.2855263 & 0.3556753\\
\hline
period4 & 0.2143646 & 0.2592105 & 0.0325346\\
\hline
sumincome\_12monthsbefore & 1.2961221 & 1.2590452 & 0.4845445\\
\hline
sumincome\_24monthsbefore & 2.7849836 & 2.6891123 & 0.3519164\\
\hline
\end{tabular}
\end{table}

\hypertarget{q3}{%
\section{Q3}\label{q3}}

Table \(\ref{tab:reg}\) below provides the regression output for the
effect of the search period on the probability of being on benefits
after 10 and 30 weeks both without and with controls. The effect of the
treatment on the 10 week mark decreases slightly in magnitude from the
naive estimate. It remains significant though at \(14.3\) percentage
points. The treatment effect increases in magnitude for being on
benefits at the 30 week mark from a 9.9 percentage point to 12.6
percentage point decrease in the probability. In both cases including
covariates maintains an economic and statistically significant treatment
effect.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m10b }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(benefits\_week10 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ searchperiod }\SpecialCharTok{+}\NormalTok{ sumincome\_12monthsbefore}\SpecialCharTok{+}\NormalTok{sumincome\_24monthsbefore}\SpecialCharTok{+}\NormalTok{age }\SpecialCharTok{+}\NormalTok{ female }\SpecialCharTok{+}\NormalTok{ children }\SpecialCharTok{+}\NormalTok{ partner }\SpecialCharTok{+}\NormalTok{ period2 }\SpecialCharTok{+}\NormalTok{period3}\SpecialCharTok{+}\NormalTok{period4 }\SpecialCharTok{+}\NormalTok{location2}\SpecialCharTok{+}\NormalTok{ location3}\SpecialCharTok{+}\NormalTok{ location4}\SpecialCharTok{+}\NormalTok{ location5}\SpecialCharTok{+}\NormalTok{ educ\_bachelormaster }\SpecialCharTok{+}\NormalTok{ educ\_prepvocational }\SpecialCharTok{+}\NormalTok{ educ\_unknown }\SpecialCharTok{+}\NormalTok{ educ\_vocational, }\AttributeTok{data =}\NormalTok{ data)}
\NormalTok{m10a }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(benefits\_week10 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ searchperiod, }\AttributeTok{data =}\NormalTok{ data)}
\NormalTok{m30b }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(benefits\_week30 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ searchperiod, }\AttributeTok{data =}\NormalTok{ data)}
\NormalTok{m30a }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(benefits\_week30 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ searchperiod }\SpecialCharTok{+}\NormalTok{ sumincome\_12monthsbefore}\SpecialCharTok{+}\NormalTok{sumincome\_24monthsbefore}\SpecialCharTok{+}\NormalTok{age }\SpecialCharTok{+}\NormalTok{ female }\SpecialCharTok{+}\NormalTok{ children }\SpecialCharTok{+}\NormalTok{ partner }\SpecialCharTok{+}\NormalTok{ period2 }\SpecialCharTok{+}\NormalTok{period3}\SpecialCharTok{+}\NormalTok{period4 }\SpecialCharTok{+}\NormalTok{location2}\SpecialCharTok{+}\NormalTok{ location3}\SpecialCharTok{+}\NormalTok{ location4}\SpecialCharTok{+}\NormalTok{ location5}\SpecialCharTok{+}\NormalTok{ educ\_bachelormaster }\SpecialCharTok{+}\NormalTok{ educ\_prepvocational }\SpecialCharTok{+}\NormalTok{ educ\_unknown }\SpecialCharTok{+}\NormalTok{ educ\_vocational, }\AttributeTok{data =}\NormalTok{ data)}

\FunctionTok{stargazer}\NormalTok{(m10a, m10b, m30a, m30b, }\AttributeTok{column.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{""}\NormalTok{, }\StringTok{"Covariates"}\NormalTok{,}\StringTok{""}\NormalTok{, }\StringTok{"Covariates"}\NormalTok{),}\AttributeTok{type =} \StringTok{"latex"}\NormalTok{,}
          \AttributeTok{title =} \StringTok{"LPM for Benefits"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{label =} \StringTok{"tab:reg"}\NormalTok{, }\AttributeTok{keep =} \FunctionTok{c}\NormalTok{(}\StringTok{"searchperiod"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!htbp] \centering 
  \caption{LPM for Benefits} 
  \label{tab:reg} 
\begin{tabular}{@{\extracolsep{5pt}}lcccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\ 
\cline{2-5} 
\\[-1.8ex] & \multicolumn{2}{c}{benefits\_week10} & \multicolumn{2}{c}{benefits\_week30} \\ 
 &  & Covariates &  & Covariates \\ 
\\[-1.8ex] & (1) & (2) & (3) & (4)\\ 
\hline \\[-1.8ex] 
 searchperiod & $-$0.164$^{***}$ & $-$0.143$^{***}$ & $-$0.099$^{***}$ & $-$0.126$^{***}$ \\ 
  & (0.023) & (0.024) & (0.025) & (0.024) \\ 
  & & & & \\ 
\hline \\[-1.8ex] 
Observations & 1,665 & 1,663 & 1,663 & 1,665 \\ 
R$^{2}$ & 0.030 & 0.067 & 0.065 & 0.016 \\ 
Adjusted R$^{2}$ & 0.029 & 0.057 & 0.054 & 0.015 \\ 
Residual Std. Error & 0.466 (df = 1663) & 0.460 (df = 1644) & 0.486 (df = 1644) & 0.496 (df = 1663) \\ 
F Statistic & 50.771$^{***}$ (df = 1; 1663) & 6.565$^{***}$ (df = 18; 1644) & 6.304$^{***}$ (df = 18; 1644) & 26.592$^{***}$ (df = 1; 1663) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\hypertarget{q4}{%
\section{Q4}\label{q4}}

All the bounds are included in the overview table in tables
\ref{tab:week10} and \ref{tab:week30} It is important to note the
direction of the treatment effect. We are looking for a negative
treatment effect, meaning that when we refer to the lower bound
(mathematically) we are referring to the most optimistic bound on the
effect size. We will make this clear in each case. The effect sizes are
also measured in decimal points and should be interpreted as percentage
point changes to the probability of being on benefits at the 10 and 30
week mark respectively. The no assumption bounds for the effect sizes
are \([-0.595, 0.405]\) at the 10 week mark and \([-0.561, 0.439]\) at
the 30 week mark. This means that the most optimistic estimate for week
10 is a decrease in the probability of being on benefits of \(59.5\)
percentage points and the least optimistic is an increase by \(40.5\)
percentage points.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probSearch }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{searchperiod)}
\NormalTok{ymin }\OtherTok{=} \DecValTok{0}
\NormalTok{ymax }\OtherTok{=} \DecValTok{1}
\CommentTok{\# we can also jsut keep it in decimals}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Benefits after 10 weeks {-} No assumption}
\NormalTok{Noass10\_LB }\OtherTok{=}\NormalTok{ prob10search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob10nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymax}
\NormalTok{Noass10\_UB }\OtherTok{=}\NormalTok{ prob10search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob10nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymin}

\CommentTok{\# Benefits after 30 weeks {-} No assumption}
\NormalTok{Noass30\_LB }\OtherTok{=}\NormalTok{ prob30search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob30nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymax}
\NormalTok{Noass30\_UB }\OtherTok{=}\NormalTok{ prob30search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob30nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymin}
\end{Highlighting}
\end{Shaded}

\hypertarget{q5}{%
\section{Q5}\label{q5}}

Here we impose the restrictions of the roy model. We assume that only
those who got the treatment benefit from it. Alternatively, this means
that those who didn't get the treatment would not benefit from it. For
the 10 week mark the bounds become \([-0.4, 0.261]\). For the 30 week
mark the bounds are \([-0.294, 0.189]\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Benefits after 10 weeks {-} Roy Model}
\NormalTok{Roy10\_LB }\OtherTok{=} \SpecialCharTok{{-}}\NormalTok{(prob10nosearch }\SpecialCharTok{{-}}\NormalTok{ ymin)}\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch)}
\NormalTok{Roy10\_UB }\OtherTok{=}\NormalTok{  (prob10search }\SpecialCharTok{{-}}\NormalTok{ ymin) }\SpecialCharTok{*}\NormalTok{ probSearch}

\CommentTok{\# Benefits after 30 weeks {-} Roy Model}
\NormalTok{Roy30\_LB }\OtherTok{=} \SpecialCharTok{{-}}\NormalTok{(prob30nosearch }\SpecialCharTok{{-}}\NormalTok{ ymin)}\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch)}
\NormalTok{Roy30\_UB }\OtherTok{=}\NormalTok{  (prob30search }\SpecialCharTok{{-}}\NormalTok{ ymin) }\SpecialCharTok{*}\NormalTok{ probSearch}
\end{Highlighting}
\end{Shaded}

\hypertarget{q6}{%
\section{Q6}\label{q6}}

MTR treatment always has a positive effect. This means that the
probability that anyone is still on benefits after 10 or 30 weeks after
treatment is always lower than if they had not received treatment. The
MTR generally only affects the lower bound, as it pushes up the
treatment effect (the worst estimate becomes better). However, in our
case a better treatment effect is a more negative number. This means it
works on our upper bound instead. This is why the upper bound becomes
zero under MTR and the lower bound remains unchanged. The bounds under
MRT for the 10 week mark the bounds become \([-0.505, 0.0]\). For the 30
week mark the bounds are \([-0.561, 0.0]\).

MTS normally affects the upper bound as it restricts the best estimate
of the treatment. In our case though this is the lower bound. The bounds
under MTS for the 10 week mark the bounds become \([-0.164, 0.405]\).
For the 30 week mark the bounds are \([-0.126, 0.439]\).

Combining both assumptions yields the MTS/MTR bounds of
\([-0.164, 0.00]\) and \([-0.126, 0.0]\) for the 10 and 30 year mark
respectively.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Benefits after 10 weeks {-} MTS/MTR}
\NormalTok{MTS10\_LB }\OtherTok{=}\NormalTok{ prob10search }\SpecialCharTok{{-}}\NormalTok{ prob10nosearch}
\NormalTok{MTS10\_UB }\OtherTok{=}\NormalTok{ prob10search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob10nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymin}

\NormalTok{MTR10\_LB }\OtherTok{=}\NormalTok{ prob10search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob10nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymax}
\NormalTok{MTR10\_UB }\OtherTok{=} \DecValTok{0}

\NormalTok{MTR\_LB}\OtherTok{=}\SpecialCharTok{{-}}\FloatTok{16.4}
\NormalTok{MTR\_UB}\OtherTok{=}\FloatTok{57.2}\SpecialCharTok{*}\FloatTok{0.4563{-}73.6}\SpecialCharTok{*}\FloatTok{0.5437}\SpecialCharTok{+}\DecValTok{100}\SpecialCharTok{*}\FloatTok{0.53437}

\NormalTok{MTSMTR10\_LB }\OtherTok{=}\NormalTok{ MTS10\_LB}
\NormalTok{MTSMTR10\_UB }\OtherTok{=}\NormalTok{ MTR10\_UB}

\NormalTok{MTSMTR\_LB}\OtherTok{=}\SpecialCharTok{{-}}\FloatTok{16.4}
\NormalTok{MTSMTR\_UB}\OtherTok{=}\DecValTok{0}

\CommentTok{\# Benefits after 30 weeks {-} MTS/MTR}
\NormalTok{MTS30\_LB }\OtherTok{=}\NormalTok{ prob30search }\SpecialCharTok{{-}}\NormalTok{ prob30nosearch}
\NormalTok{MTS30\_UB }\OtherTok{=}\NormalTok{ prob30search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob30nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymin}
  
\NormalTok{MTR30\_LB }\OtherTok{=}\NormalTok{ prob30search}\SpecialCharTok{*}\NormalTok{probSearch }\SpecialCharTok{{-}}\NormalTok{ prob30nosearch }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{+}\NormalTok{ (ymin }\SpecialCharTok{+}\NormalTok{ ymax) }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{probSearch) }\SpecialCharTok{{-}}\NormalTok{ ymax}
\NormalTok{MTR30\_UB }\OtherTok{=} \DecValTok{0}

\NormalTok{MTSMTR30\_LB }\OtherTok{=}\NormalTok{ MTS30\_LB}
\NormalTok{MTSMTR30\_UB }\OtherTok{=}\NormalTok{ MTR30\_UB}
\end{Highlighting}
\end{Shaded}

\hypertarget{q7}{%
\section{Q7}\label{q7}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prob10search\_bachelormaster }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\NormalTok{prob10nosearch\_bachelormaster }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\NormalTok{prob10search\_vocational }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_vocational}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\NormalTok{prob10nosearch\_vocational }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_vocational}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\NormalTok{prob10search\_prepvocational }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_prepvocational}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\NormalTok{prob10nosearch\_prepvocational }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_prepvocational}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\CommentTok{\# Goes against the MIV assumption!}

\NormalTok{prob10search\_primaryorless }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_primaryorless}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\NormalTok{prob10nosearch\_primaryorless }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_primaryorless}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\CommentTok{\# Does not tell us anything, so ignore}
\NormalTok{prob10search\_unknown }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_unknown}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\NormalTok{prob10nosearch\_unknown }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_unknown}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

Checking the data for the assumptions of the MIV reveals that
Vocational, Prepvocational and Primaryorless go against the MIV
assumption. We thus reduce the MIV to whether a person has a bachelor or
not, and check again whether the MIV assumption holds:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prob10search\_NObachelormaster }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{])}
\NormalTok{prob10nosearch\_NObachelormaster }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

Now, the MIV assumption holds as for both cases \(d = \{0,1\}\), the
probability of persons with a bachelor or master degree being still
unemployed after 10 weeks is lower than the probability of persons
without a bachelor or master degree. Logically this could also be
explained by the biggest difference in educational qualification
existing for those with a bachelor and master degree. In contrast, the
others may give people similarly marketable skills.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prob\_BachelorMaster }\OtherTok{=} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# MIV for Benefits after 10 weeks}

\NormalTok{prob10nosearch\_LB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{max}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }
\NormalTok{prob10nosearch\_UB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{min}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\NormalTok{prob10search\_LB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{max}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }
\NormalTok{prob10search\_UB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{min}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week10[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\NormalTok{MIV10\_LB }\OtherTok{=}\NormalTok{ prob10search\_LB }\SpecialCharTok{{-}}\NormalTok{ prob10nosearch\_LB}

\NormalTok{MIV10\_UB }\OtherTok{=}\NormalTok{ prob10search\_UB }\SpecialCharTok{{-}}\NormalTok{ prob10nosearch\_UB}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# MIV for Benefits after 30 weeks}

\NormalTok{prob30nosearch\_LB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{max}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }
\NormalTok{prob30nosearch\_UB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{min}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{0} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\NormalTok{prob30search\_LB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{max}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }
\NormalTok{prob30search\_UB }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{prob\_BachelorMaster) }\SpecialCharTok{*} \FunctionTok{min}\NormalTok{(}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]), }\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])) }\SpecialCharTok{+}\NormalTok{ prob\_BachelorMaster }\SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{benefits\_week30[data}\SpecialCharTok{$}\NormalTok{searchperiod}\SpecialCharTok{==}\DecValTok{1} \SpecialCharTok{\&}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{educ\_bachelormaster}\SpecialCharTok{==}\DecValTok{1}\NormalTok{])}

\NormalTok{MIV30\_LB }\OtherTok{=}\NormalTok{ prob30search\_LB }\SpecialCharTok{{-}}\NormalTok{ prob30nosearch\_LB}

\NormalTok{MIV30\_UB }\OtherTok{=}\NormalTok{ prob30search\_UB }\SpecialCharTok{{-}}\NormalTok{ prob30nosearch\_UB}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Dataframe with all bounds for benefits after 10 weeks}
\NormalTok{Model }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}No Assumptions\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Roy Model\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MTS\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MTR\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MTS+MTR\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MIV\textquotesingle{}}\NormalTok{)}
\NormalTok{Lowerbound }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(Noass10\_LB, Roy10\_LB, MTS10\_LB, MTR10\_LB, MTSMTR10\_LB, MIV10\_LB)}
\NormalTok{Upperbound }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(Noass10\_UB, Roy10\_UB, MTS10\_UB, MTR10\_UB, MTSMTR10\_UB, MIV10\_UB)}

\NormalTok{bounds10 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(Model, Lowerbound, Upperbound)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(bounds10, }\AttributeTok{caption =} \StringTok{"10 Week Bounds"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:unnamed-chunk-8}10 Week Bounds}
\centering
\begin{tabular}[t]{l|r|r}
\hline
Model & Lowerbound & Upperbound\\
\hline
No Assumptions & -0.5951952 & 0.4048048\\
\hline
Roy Model & -0.4000000 & 0.2612613\\
\hline
MTS & -0.1635432 & 0.4048048\\
\hline
MTR & -0.5951952 & 0.0000000\\
\hline
MTS+MTR & -0.1635432 & 0.0000000\\
\hline
MIV & -0.1610003 & -0.1696931\\
\hline
\end{tabular}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Dataframe with all bounds for benefits after 30 weeks}
\NormalTok{Model }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}No Assumptions\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Roy Model\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MTS\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MTR\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MTS+MTR\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}MIV\textquotesingle{}}\NormalTok{)}
\NormalTok{Lowerbound }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(Noass30\_LB, Roy30\_LB, MTS30\_LB, MTR30\_LB, MTSMTR30\_LB, MIV30\_LB)}
\NormalTok{Upperbound }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(Noass30\_UB, Roy30\_UB, MTS30\_UB, MTR30\_UB, MTSMTR30\_UB, MIV30\_UB)}

\NormalTok{bounds30 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(Model, Lowerbound, Upperbound)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(bounds30, }\AttributeTok{caption =} \StringTok{"30 Week Bounds"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:unnamed-chunk-8}30 Week Bounds}
\centering
\begin{tabular}[t]{l|r|r}
\hline
Model & Lowerbound & Upperbound\\
\hline
No Assumptions & -0.5609610 & 0.4390390\\
\hline
Roy Model & -0.2936937 & 0.1891892\\
\hline
MTS & -0.1258578 & 0.4390390\\
\hline
MTR & -0.5609610 & 0.0000000\\
\hline
MTS+MTR & -0.1258578 & 0.0000000\\
\hline
MIV & -0.1016627 & -0.1912732\\
\hline
\end{tabular}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bounds10}\SpecialCharTok{$}\NormalTok{Model  }\OtherTok{=} \FunctionTok{factor}\NormalTok{(bounds10}\SpecialCharTok{$}\NormalTok{Model, }\AttributeTok{levels=}\FunctionTok{c}\NormalTok{(}\StringTok{"No Assumptions"}\NormalTok{, }\StringTok{"Roy Model"}\NormalTok{, }\StringTok{"MTS"}\NormalTok{, }\StringTok{"MTR"}\NormalTok{, }\StringTok{"MTS+MTR"}\NormalTok{, }\StringTok{"MIV"}\NormalTok{))}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(reshape2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'reshape2' was built under R version 4.0.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{melt}\NormalTok{(bounds10, }\AttributeTok{id.vars=}\StringTok{"Model"}\NormalTok{, }\AttributeTok{value.name =} \StringTok{"TreatmentEffect"}\NormalTok{)}

\CommentTok{\# Everything on the same plot}
\FunctionTok{ggplot}\NormalTok{(d, }\FunctionTok{aes}\NormalTok{(Model, TreatmentEffect, }\AttributeTok{col=}\NormalTok{variable)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{( }\AttributeTok{color=}\StringTok{"grey"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{shape=}\StringTok{"{-}"}\NormalTok{, }\AttributeTok{color=}\StringTok{"\#69b3a2"}\NormalTok{, }\AttributeTok{size=}\DecValTok{15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_smooth}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{Assignment-2-updated_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m10b }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(benefits\_week10 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ searchperiod }\SpecialCharTok{+}\NormalTok{ educ\_bachelormaster }\SpecialCharTok{+}\NormalTok{ educ\_prepvocational }\SpecialCharTok{+}\NormalTok{ educ\_unknown }\SpecialCharTok{+}\NormalTok{ educ\_vocational, }\AttributeTok{data =}\NormalTok{ data)}
\NormalTok{m30a }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(benefits\_week30 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ searchperiod }\SpecialCharTok{+}\NormalTok{ educ\_bachelormaster }\SpecialCharTok{+}\NormalTok{ educ\_prepvocational }\SpecialCharTok{+}\NormalTok{ educ\_unknown }\SpecialCharTok{+}\NormalTok{ educ\_vocational, }\AttributeTok{data =}\NormalTok{ data)}

\FunctionTok{stargazer}\NormalTok{(m10a, m10b, m30a, m30b,}\AttributeTok{type =} \StringTok{"latex"}\NormalTok{,}
         \AttributeTok{title =} \StringTok{"LPM for Benefits"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!htbp] \centering 
  \caption{LPM for Benefits} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lcccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\ 
\cline{2-5} 
\\[-1.8ex] & \multicolumn{2}{c}{benefits\_week10} & \multicolumn{2}{c}{benefits\_week30} \\ 
\\[-1.8ex] & (1) & (2) & (3) & (4)\\ 
\hline \\[-1.8ex] 
 searchperiod & $-$0.164$^{***}$ & $-$0.149$^{***}$ & $-$0.116$^{***}$ & $-$0.126$^{***}$ \\ 
  & (0.023) & (0.023) & (0.024) & (0.024) \\ 
  & & & & \\ 
 educ\_bachelormaster &  & $-$0.071$^{*}$ & $-$0.181$^{***}$ &  \\ 
  &  & (0.037) & (0.040) &  \\ 
  & & & & \\ 
 educ\_prepvocational &  & 0.040 & $-$0.029 &  \\ 
  &  & (0.039) & (0.042) &  \\ 
  & & & & \\ 
 educ\_unknown &  & $-$0.358$^{***}$ & $-$0.341$^{***}$ &  \\ 
  &  & (0.072) & (0.076) &  \\ 
  & & & & \\ 
 educ\_vocational &  & 0.019 & $-$0.066$^{*}$ &  \\ 
  &  & (0.036) & (0.038) &  \\ 
  & & & & \\ 
 Constant & 0.736$^{***}$ & 0.744$^{***}$ & 0.624$^{***}$ & 0.540$^{***}$ \\ 
  & (0.016) & (0.032) & (0.034) & (0.016) \\ 
  & & & & \\ 
\hline \\[-1.8ex] 
Observations & 1,665 & 1,665 & 1,665 & 1,665 \\ 
R$^{2}$ & 0.030 & 0.054 & 0.041 & 0.016 \\ 
Adjusted R$^{2}$ & 0.029 & 0.051 & 0.038 & 0.015 \\ 
Residual Std. Error & 0.466 (df = 1663) & 0.461 (df = 1659) & 0.490 (df = 1659) & 0.496 (df = 1663) \\ 
F Statistic & 50.771$^{***}$ (df = 1; 1663) & 18.994$^{***}$ (df = 5; 1659) & 14.092$^{***}$ (df = 5; 1659) & 26.592$^{***}$ (df = 1; 1663) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\end{document}
